### ISSUE TITLE
Error css_vip

### ISSUE THREAD

**Issue by gha241** [CS-GEJMERZY/VIP-Plugin#62]
14:49:56 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Core.Plugin.OnPlayerVIPInfoCommand(CCSPlayerController player, CommandInfo commandInfo) in /home/runner/work/VIP-Plugin/VIP-Plugin/src/Commands/AdminCommands.cs:line 360
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by wohahobg** [comment]
Hey thanks I will fix this. The command is to be run only in-game.

**Comment by gha241** [comment]
> Hey thanks I will fix this. The command is to be run only in-game.

I have added VIP on the server and after entering !vip or !css_vip the information is displayed that I do not have any service :)

**Comment by wohahobg** [comment]
Is the vip by Random VIp or Night Vip or by flag? 

I have test it only via group id.

**Comment by wohahobg** [comment]
I see where the issue is. !vip work only if the record exists in the database. 

So you have to add it by the command.

I will try to find away around this in my off time.

**Comment by gha241** [comment]
> I see where the issue is. !vip work only if the record exists in the database.
> 
> So you have to add it by the command.
> 
> I will try to find away around this in my off time.

@wohahobg and how did you do something about it?

**Comment by wohahobg** [comment]
HI, I am so sorry for the late response 😄 

I have fix those issues and will be ready soon, trying few things first.

**Comment by jxn78** [comment]
@wohahobg When can we expect an update? 😁

**Comment by wohahobg** [comment]
Hi, the update is ready, and I am waiting for the pull request to be accepted. I will upload the new files here in a bit.

**Comment by wohahobg** [comment]
@jxn78 
https://github.com/wohahobg/VIP-Plugin/releases/tag/v1.1.10

Please use this version until he accept the pull request.

**Comment by jxn78** [comment]
@wohahobg I installed the latest version and VIP doesn't work, I have VIP on the flag

**Comment by jxn78** [comment]
there are no errors

admins.json
 "flags": ["@vip-plugin/vip"]

**Comment by wohahobg** [comment]
Got it. I will check it today sometime

**Comment by wohahobg** [comment]
Hi, 

That's so wired for me working just fine.

**Comment by jxn78** [comment]
ok everything works fine for me too, I didn't have a flag entered in the store ;D

**Comment by wohahobg** [comment]
Nice! Please check everything hope there won't be any issues.

**Comment by jxn78** [comment]
@wohahobg double jump only works in the first round
